/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JFrames;

/**
 *
 * @author daAkn
 */
public class Respaldo extends javax.swing.JFrame {

    /**
     * Creates new form Respaldo
     */
    public Respaldo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnIconoLupa = new javax.swing.JButton();
        lblDiagnostico = new javax.swing.JLabel();
        jScrollPaneADiagnostico = new javax.swing.JScrollPane();
        txtADiagnostico = new javax.swing.JTextArea();
        lblTratamiento = new javax.swing.JLabel();
        btnMedicamento = new javax.swing.JButton();
        jScrollPaneTablaMedReceta = new javax.swing.JScrollPane();
        tablaMedicamentosReceta = new javax.swing.JTable();
        btnConfirmar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtFNombreA = new javax.swing.JTextField();
        txtFNacimiento = new javax.swing.JTextField();
        txtFGenero = new javax.swing.JTextField();
        txtFEmisionFecha = new javax.swing.JTextField();
        txtFEmisionHora = new javax.swing.JTextField();
        txtFEdad = new javax.swing.JTextField();
        txtFPeso = new javax.swing.JTextField();
        txtFAltura = new javax.swing.JTextField();
        txtFNControl = new javax.swing.JTextField();
        txtFMedico = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(3, 102, 102));
        jPanel1.setMaximumSize(new java.awt.Dimension(610, 360));
        jPanel1.setMinimumSize(new java.awt.Dimension(610, 360));

        btnGuardar.setText("Imprimir");
        btnGuardar.setEnabled(false);
        btnGuardar.setFocusPainted(false);
        btnGuardar.setMaximumSize(new java.awt.Dimension(100, 30));
        btnGuardar.setMinimumSize(new java.awt.Dimension(100, 30));
        btnGuardar.setPreferredSize(new java.awt.Dimension(100, 30));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.setFocusPainted(false);
        btnSalir.setMaximumSize(new java.awt.Dimension(100, 30));
        btnSalir.setMinimumSize(new java.awt.Dimension(100, 30));
        btnSalir.setPreferredSize(new java.awt.Dimension(100, 30));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnIconoLupa.setBackground(new java.awt.Color(36, 130, 119));
        btnIconoLupa.setBorder(null);
        btnIconoLupa.setFocusPainted(false);
        btnIconoLupa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIconoLupaActionPerformed(evt);
            }
        });

        lblDiagnostico.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        lblDiagnostico.setForeground(new java.awt.Color(255, 255, 255));
        lblDiagnostico.setText("Diagnóstico");
        lblDiagnostico.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        txtADiagnostico.setColumns(20);
        txtADiagnostico.setRows(5);
        jScrollPaneADiagnostico.setViewportView(txtADiagnostico);

        lblTratamiento.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        lblTratamiento.setForeground(new java.awt.Color(255, 255, 255));
        lblTratamiento.setText("Tratamiento");
        lblTratamiento.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);

        btnMedicamento.setText("Agregar");
        btnMedicamento.setEnabled(false);
        btnMedicamento.setFocusPainted(false);
        btnMedicamento.setMaximumSize(new java.awt.Dimension(100, 30));
        btnMedicamento.setMinimumSize(new java.awt.Dimension(100, 30));
        btnMedicamento.setPreferredSize(new java.awt.Dimension(100, 30));
        btnMedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedicamentoActionPerformed(evt);
            }
        });

        jScrollPaneTablaMedReceta.setBackground(new java.awt.Color(0, 153, 153));
        jScrollPaneTablaMedReceta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jScrollPaneTablaMedRecetaMousePressed(evt);
            }
        });

        tablaMedicamentosReceta.setBackground(new java.awt.Color(0, 153, 153));
        tablaMedicamentosReceta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaMedicamentosReceta.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tablaMedicamentosReceta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMedicamentosRecetaMouseClicked(evt);
            }
        });
        jScrollPaneTablaMedReceta.setViewportView(tablaMedicamentosReceta);

        btnConfirmar.setBackground(new java.awt.Color(36, 130, 119));
        btnConfirmar.setBorder(null);
        btnConfirmar.setFocusPainted(false);
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(36, 130, 119));
        btnCancelar.setBorder(null);
        btnCancelar.setFocusPainted(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        txtFNombreA.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        txtFNombreA.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtFNombreA.setToolTipText("");
        txtFNombreA.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 4, 5, 4));
        txtFNombreA.setEnabled(false);
        txtFNombreA.setMargin(new java.awt.Insets(3, 8, 3, 8));
        txtFNombreA.setMaximumSize(new java.awt.Dimension(130, 30));
        txtFNombreA.setMinimumSize(new java.awt.Dimension(130, 30));
        txtFNombreA.setPreferredSize(new java.awt.Dimension(130, 30));
        txtFNombreA.setRequestFocusEnabled(false);

        txtFNacimiento.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        txtFNacimiento.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtFNacimiento.setToolTipText("");
        txtFNacimiento.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 4, 5, 4));
        txtFNacimiento.setEnabled(false);
        txtFNacimiento.setMargin(new java.awt.Insets(3, 8, 3, 8));
        txtFNacimiento.setMaximumSize(new java.awt.Dimension(130, 30));
        txtFNacimiento.setMinimumSize(new java.awt.Dimension(130, 30));
        txtFNacimiento.setPreferredSize(new java.awt.Dimension(130, 30));
        txtFNacimiento.setRequestFocusEnabled(false);

        txtFGenero.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        txtFGenero.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtFGenero.setToolTipText("");
        txtFGenero.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 4, 5, 4));
        txtFGenero.setEnabled(false);
        txtFGenero.setMargin(new java.awt.Insets(3, 8, 3, 8));
        txtFGenero.setMaximumSize(new java.awt.Dimension(130, 30));
        txtFGenero.setMinimumSize(new java.awt.Dimension(130, 30));
        txtFGenero.setPreferredSize(new java.awt.Dimension(130, 30));
        txtFGenero.setRequestFocusEnabled(false);

        txtFEmisionFecha.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        txtFEmisionFecha.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtFEmisionFecha.setToolTipText("");
        txtFEmisionFecha.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 4, 5, 4));
        txtFEmisionFecha.setEnabled(false);
        txtFEmisionFecha.setMargin(new java.awt.Insets(3, 8, 3, 8));
        txtFEmisionFecha.setMaximumSize(new java.awt.Dimension(130, 30));
        txtFEmisionFecha.setMinimumSize(new java.awt.Dimension(130, 30));
        txtFEmisionFecha.setPreferredSize(new java.awt.Dimension(130, 30));
        txtFEmisionFecha.setRequestFocusEnabled(false);

        txtFEmisionHora.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        txtFEmisionHora.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtFEmisionHora.setToolTipText("");
        txtFEmisionHora.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 4, 5, 4));
        txtFEmisionHora.setEnabled(false);
        txtFEmisionHora.setMargin(new java.awt.Insets(3, 8, 3, 8));
        txtFEmisionHora.setMaximumSize(new java.awt.Dimension(130, 30));
        txtFEmisionHora.setMinimumSize(new java.awt.Dimension(130, 30));
        txtFEmisionHora.setPreferredSize(new java.awt.Dimension(130, 30));
        txtFEmisionHora.setRequestFocusEnabled(false);

        txtFEdad.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        txtFEdad.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtFEdad.setToolTipText("");
        txtFEdad.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 4, 5, 4));
        txtFEdad.setEnabled(false);
        txtFEdad.setMargin(new java.awt.Insets(3, 8, 3, 8));
        txtFEdad.setMaximumSize(new java.awt.Dimension(130, 30));
        txtFEdad.setMinimumSize(new java.awt.Dimension(130, 30));
        txtFEdad.setPreferredSize(new java.awt.Dimension(130, 30));
        txtFEdad.setRequestFocusEnabled(false);

        txtFPeso.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        txtFPeso.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtFPeso.setToolTipText("");
        txtFPeso.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 4, 5, 4));
        txtFPeso.setMargin(new java.awt.Insets(3, 8, 3, 8));
        txtFPeso.setMaximumSize(new java.awt.Dimension(160, 30));
        txtFPeso.setMinimumSize(new java.awt.Dimension(160, 30));
        txtFPeso.setPreferredSize(new java.awt.Dimension(160, 30));

        txtFAltura.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        txtFAltura.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtFAltura.setToolTipText("");
        txtFAltura.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 4, 5, 4));
        txtFAltura.setMargin(new java.awt.Insets(3, 8, 3, 8));
        txtFAltura.setMaximumSize(new java.awt.Dimension(160, 30));
        txtFAltura.setMinimumSize(new java.awt.Dimension(160, 30));
        txtFAltura.setPreferredSize(new java.awt.Dimension(160, 30));

        txtFNControl.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        txtFNControl.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtFNControl.setToolTipText("");
        txtFNControl.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 4, 5, 4));
        txtFNControl.setMargin(new java.awt.Insets(3, 8, 3, 8));
        txtFNControl.setMaximumSize(new java.awt.Dimension(160, 30));
        txtFNControl.setMinimumSize(new java.awt.Dimension(160, 30));
        txtFNControl.setPreferredSize(new java.awt.Dimension(160, 30));

        txtFMedico.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        txtFMedico.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtFMedico.setToolTipText("");
        txtFMedico.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 4, 5, 4));
        txtFMedico.setEnabled(false);
        txtFMedico.setMargin(new java.awt.Insets(3, 8, 3, 8));
        txtFMedico.setMaximumSize(new java.awt.Dimension(130, 30));
        txtFMedico.setMinimumSize(new java.awt.Dimension(130, 30));
        txtFMedico.setPreferredSize(new java.awt.Dimension(130, 30));
        txtFMedico.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblDiagnostico)
                                .addGap(160, 160, 160)
                                .addComponent(lblTratamiento)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jScrollPaneADiagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPaneTablaMedReceta, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtFNControl, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnIconoLupa, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(9, 9, 9))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtFPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtFAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(txtFNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtFEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(txtFNombreA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtFGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtFEmisionFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtFEmisionHora, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtFMedico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(20, 20, 20))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnIconoLupa, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFNControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFNombreA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFGenero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFMedico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFNacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFEmisionFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFEmisionHora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFEdad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPaneTablaMedReceta, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPaneADiagnostico, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed

    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnIconoLupaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIconoLupaActionPerformed
        nControlA = txtFNControl.getText();

        if (!nControlA.isEmpty()) {
            String nControlExisteSQL = "SELECT Numero_Control FROM Alumno WHERE Numero_Control =" + nControlA;
            if (fn.verificarExistencia(nControlExisteSQL) == true) {
                obtenerDatosA();
                obtenerDatosM();
                cargarDatosA();
                cargarDatosM();
                txtFNControl.setEnabled(false);
                btnIconoLupa.setEnabled(false);
                btnConfirmar.setEnabled(true);
                btnConfirmar.setVisible(true);
                btnCancelar.setEnabled(true);
                btnCancelar.setVisible(true);
            } else {
                mostrarError("Alumno NO Encontrado", "El número de control no existe o no pertenece a un alumno");
            }
        } else {
            mostrarError("Campo vacio", "Escribe un numero de control");
        }
    }//GEN-LAST:event_btnIconoLupaActionPerformed

    private void btnMedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedicamentoActionPerformed

    }//GEN-LAST:event_btnMedicamentoActionPerformed

    private void tablaMedicamentosRecetaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMedicamentosRecetaMouseClicked

    }//GEN-LAST:event_tablaMedicamentosRecetaMouseClicked

    private void jScrollPaneTablaMedRecetaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPaneTablaMedRecetaMousePressed

    }//GEN-LAST:event_jScrollPaneTablaMedRecetaMousePressed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
        activarCamposReceta();
        btnConfirmar.setEnabled(false);
        btnConfirmar.setVisible(false);
        txtFPeso.setEnabled(true);
        txtFPeso.setVisible(true);
        txtFAltura.setEnabled(true);
        txtFAltura.setVisible(true);
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        desactivarCamposReceta();
        txtFNControl.setEnabled(true);
        btnCancelar.setEnabled(false);
        btnCancelar.setVisible(false);
        btnIconoLupa.setEnabled(true);
        limpiarDatos();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Respaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Respaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Respaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Respaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Respaldo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnIconoLupa;
    private javax.swing.JButton btnMedicamento;
    private javax.swing.JButton btnSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPaneADiagnostico;
    private javax.swing.JScrollPane jScrollPaneTablaMedReceta;
    private javax.swing.JLabel lblDiagnostico;
    private javax.swing.JLabel lblTratamiento;
    private javax.swing.JTable tablaMedicamentosReceta;
    private javax.swing.JTextArea txtADiagnostico;
    private javax.swing.JTextField txtFAltura;
    private javax.swing.JTextField txtFEdad;
    private javax.swing.JTextField txtFEmisionFecha;
    private javax.swing.JTextField txtFEmisionHora;
    private javax.swing.JTextField txtFGenero;
    private javax.swing.JTextField txtFMedico;
    private javax.swing.JTextField txtFNControl;
    private javax.swing.JTextField txtFNacimiento;
    private javax.swing.JTextField txtFNombreA;
    private javax.swing.JTextField txtFPeso;
    // End of variables declaration//GEN-END:variables
}
